### ISSUE TITLE
Need to add front end validation

### ISSUE THREAD

**Issue by jonahheeren** [TransformingDrainageProject/reservoir-planning-tool#33]
Currently if I enter invalid things like: Pond Volume Smallest = 300, Pond Volume Largest = 100, and steps = 2. This will still be posted to the back end and calculate num increments = -100. And as such the algorithm never executes the first for loop.

Could also have the server post back errors but I prefer to reduce as much invalid input as possible before it posts to the server.

**Comment by drewatk** [comment]
Closed by #74
